version: "2"
services:
  app:
    container_name: app

    build: .
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data
    restart: always
    ports:
      - "27017:27017"
